name: alexa-casa
dependencies:
- click=6.6=py27_0
- flask=0.12=py27_0
- itsdangerous=0.24=py27_0
- jinja2=2.8=py27_1
- markupsafe=0.23=py27_2
- openssl=1.0.2j=0
- pip=9.0.1=py27_1
- python=2.7.13=0
- readline=6.2=2
- setuptools=27.2.0=py27_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- werkzeug=0.11.11=py27_1
- wheel=0.29.0=py27_0
- zlib=1.2.8=3
- pip:
  - aniso8601==1.2.0
  - argcomplete==1.7.0
  - base58==0.2.4
  - boto3==1.4.2
  - botocore==1.4.87
  - cffi==1.9.1
  - cryptography==1.7.1
  - docutils==0.13.1
  - enum34==1.1.6
  - flask-ask==0.8.3
  - futures==3.0.5
  - hjson==2.0.2
  - idna==2.2
  - ipaddress==1.0.17
  - jmespath==0.9.0
  - kappa==0.6.0
  - lambda-packages==0.11.0
  - placebo==0.8.1
  - pyasn1==0.1.9
  - pycparser==2.17
  - pyopenssl==16.2.0
  - python-dateutil==2.6.0
  - python-slugify==1.2.1
  - pyyaml==3.12
  - requests==2.12.4
  - s3transfer==0.1.10
  - six==1.10.0
  - toml==0.9.2
  - tqdm==4.10.0
  - troposphere==1.9.0
  - unidecode==0.4.19
  - virtualenv==15.1.0
  - wsgi-request-logger==0.4.6
  - zappa==0.32.1
